[package]
name = "nicaiemu-core"
description = "Platform-independent Nicai/MStar CBE emulator core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
image.workspace = true
armv4t_emu.workspace = true
encoding_rs.workspace = true
unifont.workspace = true

[dev-dependencies]
cargo-husky = { version = "1", default-features = false, features = ["precommit-hook", "run-cargo-fmt", "run-cargo-clippy"] }
